scissor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('shortener.urls', namespace='shortener')),
]

user/urls.py
from django.urls import path
from .views import (register_user, login_user, edit_password, password_reset_request,
                     password_reset_confirm)
from django.contrib.auth.views import LogoutView


app_name = "user"

urlpatterns = [
    path("register/", register_user, name="register"),
    path("login/", login_user, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("edit-password/", edit_password, name="edit-password"),
    path("password-reset-request/", password_reset_request, name="password-reset-request"),
    path("reset-password/<uidb64>/<token>/", password_reset_confirm, name="password-reset-confirm"),
    # path("password-change/", set_new_password, name="password-change"),
]

user/models.py
from django.db.models import (UUIDField, CharField, EmailField, BooleanField,
                              DateTimeField)
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from uuid import uuid4

class CustomUserManager(BaseUserManager):
    MAX_SUPERUSERS_ALLOWED = 1
    
    def _create_user(self, email, password=None, **kwargs):
        email = self.normalize_email(email)
        user = self.model(email=email, **kwargs)
        if password:
            user.set_password(password)
        else:
            # This is for social login. Users can change to a new password later.
            user.set_unusable_password()
        user.save(using=self._db)
        
        return user
    
    def create_superuser(self, email, password, **kwargs):
        kwargs.setdefault("is_staff", True)
        kwargs.setdefault("is_superuser", True)
        
        if self.filter(is_superuser=True).count() >= self.MAX_SUPERUSERS_ALLOWED:
            raise ValueError("Superuser account limit reached")
        
        return self._create_user(email, password, **kwargs)
    
    def create_user(self, email, password=None, **kwargs):
        kwargs.setdefault("is_staff", False)
        kwargs.setdefault("is_superuser", False)
        
        return self._create_user(email, password, **kwargs)
    

# Model for user [authentication/authorization]
class UserModel(AbstractBaseUser, PermissionsMixin):
    id = UUIDField(primary_key=True, editable=False, default=uuid4)
    username = CharField(max_length=120, unique=True, blank=True)
    email = EmailField(max_length=255, unique=True)
    password = CharField(max_length=255)
    is_active = BooleanField(default=True)
    is_staff = BooleanField(default=False)
    is_superuser = BooleanField(default=False)
    created_at = DateTimeField(auto_now_add=True, editable=False)
    last_login = DateTimeField(auto_now=True, editable=False)
    
    objects = CustomUserManager()
    
    USERNAME_FIELD = "email"
    
    class Meta:
        ordering = ["-created_at"]
    
    def __str__(self):
        return self.email

user/forms.py
from django.forms import (ModelForm, CharField, PasswordInput, ValidationError,
                           Form, EmailInput)
from .models import UserModel
from django.db.models import Q


# Form for user registration
class UserRegistrationForm(ModelForm):
    password1 = CharField(label="Enter Password", widget=PasswordInput)
    password2 = CharField(label="Repeat Password", widget=PasswordInput)
    
    class Meta:
        model = UserModel
        fields = ["email", "username"]
        
    def clean_password2(self):
        cleaned_form_data = self.cleaned_data
        if cleaned_form_data["password1"] != cleaned_form_data["password2"]:
            raise ValidationError("Passwords do not match")
        
        return cleaned_form_data["password2"]
    
    def clean_email(self):
        cleaned_form_data = self.cleaned_data
        if UserModel.objects.filter(email=cleaned_form_data["email"]).exists():
            raise ValidationError("A user with this email already exists.")
        
        return cleaned_form_data["email"]
    
    def clean_username(self):
        cleaned_form_data = self.cleaned_data
        if UserModel.objects.filter(username=cleaned_form_data["username"]).exists():
            raise ValidationError("A user with this username already exists.")
        
        return cleaned_form_data["username"]
    
    
class UserLoginForm(Form):
    email_name = CharField(label="Enter Email/Username")
    password = CharField(label="Enter Password", widget=PasswordInput)
    
    def clean_email_name(self):
        email_name = self.cleaned_data["email_name"]
        if not UserModel.objects.filter(
            Q(email=email_name) | Q(username=email_name)
        ).exists():
            raise ValidationError("Invalid email/username.")
        
        return email_name
    
    
class UserPasswordEditForm(Form):
    password1 = CharField(label="Enter Old Password", widget=PasswordInput)
    password2 = CharField(label="Enter New Password", widget=PasswordInput)
    password3 = CharField(label="Repeat New Password", widget=PasswordInput)
    
    def clean_password3(self):
        cleaned_form_data = self.cleaned_data
        if cleaned_form_data["password2"] != cleaned_form_data["password3"]:
            raise ValidationError("Passwords do not match")
        
        return cleaned_form_data["password2"]
    
    
class UserSocialPasswordEditForm(Form):
    password1 = CharField(label="Enter Password", widget=PasswordInput)
    password2 = CharField(label="Repeat Password", widget=PasswordInput)
    
    def clean_password2(self):
        cleaned_form_data = self.cleaned_data
        if cleaned_form_data["password1"] != cleaned_form_data["password2"]:
            raise ValidationError("Passwords do not match")
        
        return cleaned_form_data["password2"]
    
    
class PasswordResetRequestForm(Form):
    email = CharField(label="Enter Email", widget=EmailInput)
    
    def clean_email(self):
        email = self.cleaned_data["email"]
        if not UserModel.objects.filter(email=email).exists():
            raise ValidationError("Invalid email address")
        
        return email
    
    
class PasswordChangeForm(UserSocialPasswordEditForm):
    password1 = CharField(label="Enter New Password", widget=PasswordInput)

user/views.py
from django.shortcuts import render
from .forms import (UserRegistrationForm, UserModel, UserLoginForm, UserPasswordEditForm,
                     UserSocialPasswordEditForm, PasswordResetRequestForm, PasswordChangeForm)
from django.http import HttpResponseRedirect
from django.db.transaction import atomic
from django.contrib.auth import authenticate, login
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from .utils import send_reset_mail, DecodeResetToken
from django.core.exceptions import ValidationError
from django.shortcuts import redirect
from django.urls import reverse


def register_user(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            
            with atomic():
                UserModel.objects.create_user(email=email, password=password, username=username)

            return HttpResponseRedirect("/login/")

        return render(request, "register.html", {"form": form})

    form = UserRegistrationForm()
    return render(request, "register.html", {"form": form})


def login_user(request):
    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            email_name = form.cleaned_data["email_name"]
            password = form.cleaned_data["password"]
            user = UserModel.objects.filter(
                Q(email=email_name) | Q(username=email_name)
            ).first()
            
            user = authenticate(request,
                username=user.email,
                password=password
            )
            
            if user:
                if user.is_active:
                    login(request, user)
                    return redirect(reverse("shortener:dashboard"))
                
                form.add_error(None, "Inactive user account detected.")
            
            form.add_error(None, "Invalid login credentials.")
        
        return render(request, "login.html", {"form": form})
    
    form = UserLoginForm()
    return render(request, "login.html", {"form": form})


@login_required
def edit_password(request):
    user = request.user
    if not user.has_usable_password(): 
        if request.method == "POST":
            form = UserSocialPasswordEditForm(request.POST)
            if form.is_valid():
                password = form.cleaned_data["password1"]
                user.set_password(password)
                
                with atomic():
                    user.save()

                return redirect(reverse("user:dashboard"))

            return render(request, "edit_password.html", {"form": form})

        form = UserSocialPasswordEditForm()
        return render(request, "edit_password.html", {"form": form})
    
    else:
        if request.method == "POST":
            form = UserPasswordEditForm(request.POST)
            if form.is_valid():
                if check_password(form.cleaned_data["password1"], user.password):
                    password = form.cleaned_data["password2"]
                    user.set_password(password)
                    
                    with atomic():
                        user.save()

                    return redirect(reverse("user:dashboard"))
                
                form.add_error(None, "Incorrect password detected.")

            return render(request, "edit_password.html", {"form": form})

        form = UserPasswordEditForm()
        return render(request, "edit_password.html", {"form": form})


def password_reset_request(request):
    if request.method == "POST":
        form = PasswordResetRequestForm(request.POST)
        if form.is_valid():
            user = UserModel.objects.filter(
                email=form.cleaned_data["email"]
            ).first()
            send_reset_mail(user)
            return render(request, "password_reset_redirect.html")
        
        return render(request, "password_reset_request.html", {"form": form})
    
    form = PasswordResetRequestForm()
    return render(request, "password_reset_request.html", {"form": form})
    
    
def password_reset_confirm(request, uidb64, token):
    try:
        decoder = DecodeResetToken(uidb64, token)
        decoder.token_check()
        if request.method == "POST":
            form = PasswordChangeForm(request.POST)
            if form.is_valid():
                password = form.cleaned_data["password1"]
                user = decoder.get_user()
                with atomic():
                    user.set_password(password)
                    user.save()
                    
                return HttpResponseRedirect("/login/")
            
            return render(request, "password_change.html", {"form": form})
        
        form = PasswordChangeForm()
        return render(request, "password_change.html", {"form": form})
        
    except ValidationError:
        return render(request, "error_400.html", {"error_message": "Invalid token detected."})

user/templates/edit_password.html
{% extends "base.html" %}
{% block title %}Edit Password{% endblock %}
{% block content %}
    <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="SAVE PASSWORD">
    </form>
{% endblock %}

user/templates/error_400.html
<!DOCTYPE html>
<html>
<head>
    <title>Password Reset Request</title>
</head>
    <body>
        <h1>ERROR 400: BAD REQUEST</h1>
        <p>Detail: {{ error_message }}</p>
    </body>
</html>

user/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="LOGIN">
    </form>
    <b>
    <p>
        <a href="{% url 'social:begin' 'twitter' %}">
            LOGIN WITH TWITTER
        </a>
    </p>
    <p>
        <a href="{% url 'social:begin' 'google-oauth2' %}">
            LOGIN WITH GOOGLE
        </a>
    </p>
    <p>
        <a href="{% url 'user:password-reset-request' %}">
            FORGOT PASSWORD?
        </a>
    </p>
{% endblock %}

user/templates/password_change.html
{% extends "base.html" %}
{% block title %}Set New Password{% endblock %}
{% block content %}
    <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="SAVE PASSWORD">
    </form>
{% endblock %}

user/templates/password_reset_redirect.html
{% extends "base.html" %}
{% block title %}Password Reset{% endblock %}
{% block content %}
    <p>
        An email has been sent to your provided email address with instructions for resetting your password.
    </p>
    <p>
        If you did not receive an email, please <a href="{% url 'user:password-reset-request' %}">try again</a> with the email address you signed up with.
    </p>
{% endblock %}

user/templates/password_reset_request.html
{% extends "base.html" %}
{% block title %}Request Password Reset{% endblock %}
{% block content %}
    <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="SEND EMAIL">
    </form>
{% endblock %}

user/templates/register.html
{% extends "base.html" %}
{% block title %}Registration{% endblock %}
{% block content %}
    <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="REGISTER">
    </form>
    <p>
        <a href="{% url 'social:begin' 'twitter' %}">
            REGISTER WITH TWITTER
        </a>
    </p>
    <p>
        <a href="{% url 'social:begin' 'google-oauth2' %}">
            REGISTER WITH GOOGLE
        </a>
    </p>
{% endblock %}

user/templates/reset_email_message.html
<!DOCTYPE html>
<html>
<head>
    <title>Password Reset Request</title>
</head>
    <body>
        <p>Please click on the following link to reset your password:</p>
        <p><a href="%%SERVER_NAME%%/user/reset-password/%%UIDB64%%/%%TOKEN%%/">Reset Password</a></p>
        <p>If you did not make this request, kindly ignore this email.</p>
    </body>
</html>