scissor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('shortener.urls', namespace='shortener')),
]

shortener/urls.py
from django.urls import path
from .views import (home, dashboard, shorten, custom_shorten,
                    delete_url, edit_url, redirection, generate_qrcode)


app_name = "shortener"

urlpatterns = [
    path("", home, name="home"),
    path("dashboard/", dashboard, name="dashboard"),
    path("shorten/", shorten, name="shorten"),
    path("custom-shorten/", custom_shorten, name="custom-shorten"),
    path("delete/<uuid:url_id>/", delete_url, name="delete"),
    path("edit/<uuid:url_id>/", edit_url, name="edit"),
    path("<str:url>/", redirection, name="redirection"),
    path("generate-qr/<str:url>/", generate_qrcode, name="generate-qr-code")
]

user/urls.py
from django.urls import path
from .views import (register_user, login_user, edit_password, password_reset_request,
                     password_reset_confirm)
from django.contrib.auth.views import LogoutView


app_name = "user"

urlpatterns = [
    path("register/", register_user, name="register"),
    path("login/", login_user, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("edit-password/", edit_password, name="edit-password"),
    path("password-reset-request/", password_reset_request, name="password-reset-request"),
    path("reset-password/<uidb64>/<token>/", password_reset_confirm, name="password-reset-confirm"),
    # path("password-change/", set_new_password, name="password-change"),
]

shortener/models.py
from django.db.models import (Model, UUIDField, URLField, CharField,
                              DateTimeField, IntegerField, ForeignKey, CASCADE)
from uuid import uuid4
from django.conf import settings

# Model for short url
class ShortUrlModel(Model):
    id = UUIDField(primary_key=True, editable=False, default=uuid4)
    original_url = URLField(max_length=500, null=False, blank=False)
    short_url = CharField(max_length=120, unique=True, null=False)
    click_count = IntegerField(default=0)
    created_at = DateTimeField(auto_now_add=True)
    user = ForeignKey(settings.AUTH_USER_MODEL, related_name="shortened_urls", on_delete=CASCADE)
    
    class Meta:
        ordering = ["-created_at"]
        
    def __str__(self):
        return str(self.id)
    

class CustomUrlModel(Model):
    id = UUIDField(primary_key=True, editable=False, default=uuid4)
    original_url = URLField(max_length=500, blank=False)
    custom_url = CharField(max_length=120, unique=True, blank=False)
    click_count = IntegerField(default=0)
    created_at = DateTimeField(auto_now_add=True)
    user = ForeignKey(settings.AUTH_USER_MODEL, related_name="custom_shortened_urls", on_delete=CASCADE)
    
    class Meta:
        ordering = ["-created_at"]
        
    def __str__(self):
        return str(self.id)

shortener/forms.py
from django.forms import ModelForm
from .models import ShortUrlModel, CustomUrlModel
from .utils import url_cleaner, check_url


# Form for short url
class ShortenUrlForm(ModelForm):
    class Meta:
        model = ShortUrlModel
        fields = ["original_url"]
        
    def clean_original_url(self):
        url = self.cleaned_data["original_url"]
        return url_cleaner(url)
    

# Form for custom url
class CustomUrlForm(ModelForm):
    class Meta:
        model = CustomUrlModel
        fields = ["original_url", "custom_url"]
    
    def clean_original_url(self):
        url = self.cleaned_data["original_url"]
        return url_cleaner(url)
    
    def clean_custom_url(self):
        url = self.cleaned_data["custom_url"]
        return check_url(url)
    

# Form for editing custom url
class EditCustomUrlForm(ModelForm):
    class Meta:
        model = CustomUrlModel
        fields = ["custom_url"]
        labels = {"custom_url": "New custom url"}
        
    def clean_custom_url(self):
        url = self.cleaned_data["custom_url"]
        return check_url(url)

shortener/views.py
from django.shortcuts import render, redirect
from .forms import (ShortUrlModel, CustomUrlModel, ShortenUrlForm, CustomUrlForm,
                    EditCustomUrlForm)
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse
from .utils import generate_short_url
from qrcode import QRCode
from qrcode.constants import ERROR_CORRECT_M
from io import BytesIO
from django.db.transaction import atomic
from django.contrib.auth.decorators import login_required


server_name = settings.SERVER_NAME


def home(request):
    return render(request, "home.html")


@login_required
def dashboard(request):
    user = request.user
    urls = ShortUrlModel.objects.filter(user=user).all()
    custom_urls = CustomUrlModel.objects.filter(user=user).all()
    return render(
        request,
        "dashboard.html",
        {"urls": urls, "custom_urls": custom_urls, "server_name": server_name},
    )


@login_required
def shorten(request):
    if request.method == "POST":
        form = ShortenUrlForm(request.POST)
        if form.is_valid():
            short_url = generate_short_url()
            
            # Create and save URLs
            new_url = ShortUrlModel.objects.create(
                short_url=short_url, user=request.user, **form.cleaned_data
            )
            with atomic():
                new_url.save()
                
            return HttpResponseRedirect("/dashboard/")

        return render(request, "shortener/short_url.html", {"form": form})

    form = ShortenUrlForm()
    return render(request, "shortener/short_url.html", {"form": form})


@login_required
def custom_shorten(request):
    if request.method == "POST":
        form = CustomUrlForm(request.POST)
        if form.is_valid():
            # Create and save URLs
            new_url = CustomUrlModel.objects.create(
                user=request.user, **form.cleaned_data
                )
            with atomic():
                new_url.save()
            return HttpResponseRedirect("/dashboard/")

        return render(request, "shortener/custom_url.html", {"form": form})

    form = CustomUrlForm()
    return render(request, "shortener/custom_url.html", {"form": form})


@login_required
def delete_url(request, url_id):
    if request.method == "POST":
        user = request.user
        short_url = ShortUrlModel.objects.filter(id=url_id, user=user).first()
        custom_url = CustomUrlModel.objects.filter(id=url_id, user=user).first()

        if short_url:
            with atomic():
                short_url.delete()

        if custom_url:
            with atomic():
                custom_url.delete()

        return HttpResponseRedirect("/dashboard/")


@login_required
def edit_url(request, url_id):
    if request.method == "POST":
        user = request.user
        form = EditCustomUrlForm(
            request.POST, instance=CustomUrlModel.objects.filter(id=url_id, user=user).first()
        )
        if form.is_valid():
            with atomic():
                form.save()
            return HttpResponseRedirect("/dashboard/")

        return render(request, "shortener/edit.html", {"form": form})

    form = EditCustomUrlForm()
    return render(request, "shortener/edit.html", {"form": form})


def redirection(request, url):
    short_url = ShortUrlModel.objects.filter(short_url=url).first()
    custom_url = CustomUrlModel.objects.filter(custom_url=url).first()

    if short_url:
        with atomic():
            short_url.click_count += 1
            short_url.save()
        return redirect(short_url.original_url)

    if custom_url:
        with atomic():
            custom_url.click_count += 1
            custom_url.save()
        return redirect(custom_url.original_url)

    return HttpResponseRedirect("/dashboard/")


def generate_qrcode(request, url):
    short_url = ShortUrlModel.objects.filter(short_url=url).first()
    custom_url = CustomUrlModel.objects.filter(custom_url=url).first()
    if not (short_url, custom_url):
        return HttpResponseRedirect("/dashboard/")

    qr = QRCode(
        version=2,
        error_correction=ERROR_CORRECT_M,
        box_size=5,
        border=1,
    )
    qr.add_data(server_name + "/" + url)
    qr.make(fit=True)

    img = qr.make_image(fill_color="lime", back_color="black")
    image_buffer = BytesIO()
    img.save(image_buffer)
    image_buffer.seek(0)

    return HttpResponse(image_buffer, content_type="image/png")

shortener/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <div>
            {% if not request.user.is_authenticated %}
                <h4><a href="{% url 'shortener:home' %}">HOME</a></h4>
                <br>
                <h4><a href="{% url 'user:register' %}">REGISTER</a></h4>  
                <br>
                <h4><a href="{% url 'user:login' %}">LOGIN</a></h4>  
                <br>
            {% else %}
                <h4><a href="{% url 'shortener:dashboard' %}">DASHBOARD</a></h4>  
                <br>
                <h4><a href="{% url 'shortener:shorten' %}">SHORTEN</a></h4>
                <br>
                <h4><a href="{% url 'shortener:custom-shorten' %}">CUSTOM-SHORTEN</a></h4>
                <br>
                <h4><a href="{% url 'user:edit-password' %}">EDIT PASSWORD</a></h4>
                <br>
                <form action="{% url 'user:logout' %}" method="post">  
                    {% csrf_token %}
                    <button type="submit">LOGOUT</button>
                </form>
                <br>
            {% endif %}
        </div>
        <div>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

shortener/templates/dashboard.html
{% extends "home.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
    <div>
        <h1><b>RECENT SHORT URLS</b></h1>
    </div>
    <br>
    <div>
        {% for url in urls %}
            <p>Original URL: {{url.original_url}}</p>
            <p>Short URL: {{server_name}}/{{url.short_url}}</p>
            <p>Created: {{url.created_at}}</p>
            <p>Clicks: {{url.click_count}}</p>
            <div>
                <form action="{% url 'shortener:delete' url.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit">DELETE</button>
                </form>
                <button>QR CODE</button>
            </div>
        {% endfor %}
    </div>
    <br>
    <div>
        <h1><b>RECENT CUSTOM URLS</b></h1>
    </div>
    <br>
    <div>
        {% for url in custom_urls %}
            <p>Original URL: {{url.original_url}}</p>
            <p>Custom URL: {{server_name}}/{{url.custom_url}}</p>
            <p>Created: {{url.created_at}}</p>
            <p>Clicks: {{url.click_count}}</p>
            <div>
                <a href="{% url 'shortener:edit' url.id %}"><button>EDIT</button></a>
                <form action="{% url 'shortener:delete' url.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit">DELETE</button>
                </form>
                <button>QR CODE</button>
            </div>
        {% endfor %}
    </div>
{% endblock %}

shortener/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %} 
{% block content %}
<div>
    <h1><b>SHORTEN. COPY. SHARE.</b></h1>
</div>
{% endblock %}